version: '3.8'
services:
  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    hostname: redis
    network_mode: bridge
    ports:
      - '6379:6379/tcp'
  db:
    image: postgres:15.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local